;;(require 'ess) 
;;(R) 
;;(setq ess-eval-visibly-p nil)
;;(find-file "E:/projects/software/ps2012r_intro/test/test.R") 
;;(switch-to-buffer "test.R") 
;;(ess-eval-buffer "test.R")
(find-file "E:/projects/software/ps2012r_intro/test/test.org") 
(switch-to-buffer "test.org") 
(org-babel-tangle-file)